name: roaster_repository
description: A Lakone Roaster API Package
version: 2.2.0
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.1.3
  flutter_bluetooth_serial: ^0.4.0
#  flutter_blue:
#    path: packages/flutter_blue-enhanced
  app_settings: ^4.1.6
#  app_settings:
#    path: packages/app_settings-enhanced
  equatable: ^2.0.3
  enum_to_string: ^2.0.1
  rxdart: ^0.27.0
  permission_handler: 9.2.0
  device_info_plus: ^3.2.2

dependency_overrides:
  flutter_bluetooth_serial:
    git:
      url: https://github.com/calmh/flutter_bluetooth_serial.git
      ref: android12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
